export type {
  ApplyFailure,
  ApplyReport,
  BrokenLinkPresentation,
  ChangeSetProposal,
  CompatibilityFinding,
  Concept,
  ConceptLink,
  ConformanceFinding,
  CurationFinding,
  ExpectedContent,
  FileChangeProposal,
  Finding,
  FindingCategory,
  FindingSeverity,
  GraphEdge,
  GraphNode,
  GraphPayload,
  GraphStatistics,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  LinkClassification,
  NormalizedFrontmatter,
  OperationProblem,
  OperationResult,
  ParsedBundle,
  ParsedFrontmatter,
  ParseFailure,
  ReservedDocument,
  ReservedDocumentKind,
  SourceDocument,
  SourcePosition,
  SourceRange,
} from './types.js';
export { OKF_SEMANTIC_LIMITS } from './resource-limits.js';
export {
  hasUnpairedUtf16Surrogate,
  relativePathBoundFailure,
  utf8ByteLength,
  type RelativePathBoundFailure,
} from './text-bounds.js';
