import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = resolve(repositoryRoot, 'RUST_THIRD_PARTY_NOTICES.md');
const allowedLicenses = new Set([
  'Apache-2.0',
  'BSD-3-Clause',
  'BSL-1.0',
  'ISC',
  'MIT',
  'Unicode-3.0',
  'Unlicense',
  'Zlib',
]);

const metadata = JSON.parse(
  execFileSync('cargo', ['metadata', '--locked', '--format-version', '1'], {
    cwd: repositoryRoot,
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  }),
);
const packages = new Map(metadata.packages.map((item) => [item.id, item]));
const nodes = new Map(metadata.resolve.nodes.map((item) => [item.id, item]));
const wasmPackage = metadata.packages.find(
  (item) => item.name === 'okf-wasm' && item.source === null,
);
if (wasmPackage === undefined) {
  throw new Error('Cargo metadata does not contain the workspace okf-wasm package.');
}

const reachable = new Set();
const pending = [wasmPackage.id];
while (pending.length > 0) {
  const id = pending.pop();
  if (id === undefined || reachable.has(id)) continue;
  reachable.add(id);
  for (const dependency of nodes.get(id)?.deps ?? []) {
    pending.push(dependency.pkg);
  }
}

const dependencies = [...reachable]
  .map((id) => packages.get(id))
  .filter((item) => item?.source?.startsWith('registry+') === true)
  .sort(
    (left, right) =>
      left.name.localeCompare(right.name) || left.version.localeCompare(right.version),
  );

function validateLicense(item) {
  if (typeof item.license !== 'string' || item.license.length === 0) {
    throw new Error(`${item.name}@${item.version} does not declare an SPDX license.`);
  }
  const identifiers = item.license.match(/[A-Za-z0-9.-]+/gu) ?? [];
  const meaningful = identifiers.filter(
    (identifier) => !['AND', 'OR', 'WITH'].includes(identifier),
  );
  const rejected = meaningful.filter((identifier) => !allowedLicenses.has(identifier));
  if (rejected.length > 0) {
    throw new Error(
      `${item.name}@${item.version} uses a license outside the Rust allowlist: ${rejected.join(', ')}`,
    );
  }
}

function licenseTexts(item) {
  const directory = dirname(item.manifest_path);
  const names = readdirSync(directory)
    .filter((name) => /^(?:copying|license|notice)(?:[.-].*)?$/iu.test(name))
    .sort((left, right) => left.localeCompare(right));
  if (names.length === 0) {
    throw new Error(`${item.name}@${item.version} has no discoverable license or notice file.`);
  }
  return names.map((name) => ({
    name,
    text: readFileSync(resolve(directory, name), 'utf8').replace(/\r\n?/gu, '\n').trimEnd(),
  }));
}

const records = dependencies.map((item) => {
  validateLicense(item);
  return { item, texts: licenseTexts(item) };
});

const lines = [
  '<!-- Generated by scripts/rust-notices.mjs; do not edit manually. -->',
  '',
  '# Rust/Wasm Third-Party Notices',
  '',
  'This inventory is derived from the committed Cargo.lock dependency graph reachable from `okf-wasm`. It covers code linked into `dist/okf_core.wasm`; workspace crates are covered by the project MIT License.',
  '',
  `Rust/Wasm third-party package count: **${String(records.length)}**`,
  '',
  '| Crate | Version | SPDX license |',
  '| --- | --- | --- |',
  ...records.map(
    ({ item }) =>
      `| [${item.name}](https://crates.io/crates/${item.name}/${item.version}) | ${item.version} | ${item.license} |`,
  ),
  '',
  '## License and notice texts',
  '',
];

for (const { item, texts } of records) {
  lines.push(`### ${item.name}@${item.version}`, '');
  for (const { name, text } of texts) {
    const digest = createHash('sha256').update(text).digest('hex').slice(0, 12);
    lines.push(`Source: \`${name}\` (SHA-256 prefix \`${digest}\`)`, '', '<pre>');
    lines.push(text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;'));
    lines.push('</pre>', '');
  }
}

const generated = `${lines.join('\n').trimEnd()}\n`;
if (process.argv.includes('--write')) {
  writeFileSync(outputPath, generated, 'utf8');
  console.log(`Wrote ${outputPath}.`);
} else {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== generated) {
    throw new Error('RUST_THIRD_PARTY_NOTICES.md is stale; run npm run rust:notices:write.');
  }
  console.log(`Verified ${String(records.length)} Rust/Wasm dependency notices.`);
}
